name: Runs the tests for library modules
run-name: Executed by ${{ github.actor }}
on:
  pull_request:
  workflow_dispatch:

jobs:
  modules-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Avocado to run tests
        run: pip3 install avocado-framework==102.0

      - name: Run the ar module test
        run: ./tests/test-module.py metadata/autils/archive/ar.yml

  static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: run static checks
        uses: avocado-framework/avocado-ci-tools@main
        with:
          avocado-static-checks: true
